name: Hello World
on: 
  workflow_dispatch: 
jobs:
  hello-job:
    runs-on: ubuntu-latest
    steps:
      - name: Build Docker
        run: | 
          sudo apt install docker -y
          sudo docker run nginx
          netstat -ltnp
          curl localhost:80
