name: Hello World
'on': push
jobs:
  hello-job:
    runs-on: ubuntu-latest
    steps:
      - name: Echo text
        env: 
          RUNNER_ALLOW_RUNASROOT: 1
        run: | 
          echo "Hello, world!"
          apt install docker
          docker run nginx
          curl -Il http://localhost:80
