name: Hello World
'on': push
jobs:
  hello-job:
    runs-on: ubuntu-latest
    steps:
      - name: Echo text
        run: | 
          echo "Hello, world!"
          sudo apt install nginx
          sudo systemctl restart nginx
          sleep 10s
          curl -Il http://localhost:80
